version: 2

models:
  - name: dim_host
    description: "Host Dimension SCD Type 2 built from host_snapshot"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - host_id
            - record_start_date     # or dbt_valid_from if you use dbt snapshot columns
    columns:
      - name: host_id
        tests:
          - not_null
      - name: record_start_date
        tests:
          - not_null
      - name: record_end_date
      - name: is_current

  - name: dim_property
    description: "Property dimension (SCD2) built from property_snapshot."
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - listing_id
            - record_start_date
    columns:
      - name: listing_id
        description: "Key for listings."
        tests:
          - not_null
      - name: property_type
      - name: room_type
      - name: accommodates
      - name: record_start_date
        tests:
          - not_null
      - name: record_end_date
      - name: is_current
      
  - name: dim_suburb
    description: "Static suburb dimension from listing_neighbourhood."
    columns:
      - name: suburb_id
        description: "Primary key for dim_suburb."
        tests: [not_null, unique]
      - name: suburb_name
        tests: [not_null]
         
  - name: fact_listings
    description: "Monthly listing fact table"
    columns:
      - name: listing_id
        description: "Foreign key to dim_listing"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_property')
                field: listing_id

      - name: host_id
        description: "Foreign key to dim_host"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_host')
                field: host_id