name: 'bde_at3_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets: ["target", "dbt_packages"]

models:
  bde_at3_dbt:
    # (optional) project-wide default
    +materialized: table

    bronze:
      +schema: bronze
      +materialized: table

    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      star:
        +materialized: table
      mart:
        +materialized: view

snapshots:
  bde_at3_dbt:
    +target_schema: silver

flags:
  require_generic_test_arguments_property: true