version: 2

models:

  # ────────────────────────────────
  # Airbnb Clean
  # ────────────────────────────────
  - name: silver_airbnb_clean
    description: "Cleaned Airbnb raw data with standardized types and null handling."
    columns:
      - name: listing_id
        tests: [not_null]
      - name: host_id
        tests: [not_null]
      - name: scraped_date
        tests: [not_null]

  # ────────────────────────────────
  # Census G01 Clean (Population / Age)
  # ────────────────────────────────
  - name: silver_census_g01_clean
    description: "Cleaned Census G01 data with population and age breakdowns per LGA."
    columns:
      - name: lga_code
        tests: [not_null, unique]
      - name: population_total
        tests: [not_null]

  # ────────────────────────────────
  # Census G02 Clean (Socioeconomic)
  # ────────────────────────────────
  - name: silver_census_g02_clean
    description: "Cleaned Census G02 data with socioeconomic indicators per LGA."
    columns:
      - name: lga_code
        tests: [not_null, unique]
      - name: median_age_persons
        tests: [not_null]

  # ────────────────────────────────
  # Host (latest per host)
  # ────────────────────────────────
  - name: silver_host
    description: "Latest available host data, one row per host_id."
    columns:
      - name: host_id
        tests: [not_null]
      - name: host_name
        tests: [not_null]
      - name: host_neighbourhood
        tests: [not_null]

  # ────────────────────────────────
  # LGA Code Clean
  # ────────────────────────────────
  - name: silver_lga_code_clean
    description: "Unique LGA codes and names as the canonical key for all geography joins."
    columns:
      - name: lga_code
        tests: [not_null, unique]
      - name: lga_name
        tests: [not_null]

  # ────────────────────────────────
  # LGA Combined (Suburb to LGA map)
  # ────────────────────────────────
  - name: silver_lga
    tests:
      # guarantees 1:1 map: one row per suburb_name
      - unique:
          column_name: suburb_name
    columns:
      - name: suburb_name
        tests: [not_null]
      - name: lga_code
        tests:
          - relationships:
              to: ref('silver_lga_code_clean')
              field: lga_code

  # ────────────────────────────────
  # Listing (Monthly de-duplicated)
  # ────────────────────────────────
  - name: silver_listing
    description: "One row per listing per month, latest scrape kept."
    columns:
      - name: listing_id
        tests: [not_null]
      - name: host_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('silver_host')
                field: host_id
      - name: month
        tests: [not_null]